### ISSUE TITLE
Not showing properly on Firefox 31

### ISSUE THREAD

**Issue by aps-sids** [ebidel/material-playground#2]
![screen shot 2014-08-14 at 17 18 36](https://cloud.githubusercontent.com/assets/2363074/3919488/0807d798-23a9-11e4-934f-1d588f8d7d74.png)

-----------

![screen shot 2014-08-14 at 17 18 45](https://cloud.githubusercontent.com/assets/2363074/3919487/0801adaa-23a9-11e4-9678-15510aa6f880.png)

**Comment by ebidel** [comment]
Closing. This is pretty old and I just updated to 1.0
